Game Simulator:

  # Game type - either Nim or Ledge
  game_type: "nim"

  # Number of games in a batch
  batch_size: 64

  # Starting player option - should player 1 or player 2 start
  starting_player: 1

  # Number of simulations (and hence roll-outs) per actual game move
  number_of_simulations_per_game_move: 10

  # Turn on/off game statistics
  verbose: 1

  Nim:

    # Number of pieces on the board
    n: 5

    # Maximum number of pieces a player can move from the board at their turn
    k: 2

  Ledge:

    # Number of cells on the one-dimensional board
    l: 10
