Game Simulator:

  # Game type - either Nim or Ledge
  game_type: "ledge"

  # G - Number of games in a batch
  episodes: 10

  # P - Starting player option - could be Player 1, 2 or 3 (random)
  starting_player: 1

  # M - Number of simulations (and hence roll-outs) per actual game move
  num_sim: 500

  # Turn on/off game statistics
  verbose: 0

  Game:
    # Exploration constant
    c: 1

    Nim:

      # Number of pieces on the board
      n: 10

      # Maximum number of pieces a player can move from the board at their turn
      k: 2

    Ledge:

      # The initial board of the game
      board_init: [0,0,0,1,0,2,0,0,1,0]
